stages:
- name: 编译
  image: maven:3.6-alpine
  command:
  - mvn package
  tty: true
  env:
  - name: CONTAINER_ENV_VAR
  value: maven
  volumeMounts:
  - name: repo-maven-cache
  mountPath: /root/.m2
- name: 发布镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: java-maven-demo
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
