apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-demo-deployment
  labels:
    app: java-maven-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-demo
  template:
    metadata:
      labels:
        app: java-maven-demo
    spec:
      containers:
      - name: java-maven-demo
        image: java-maven-demo:v1
        ports:
        - containerPort: 40080